### ISSUE TITLE
Crash FORGE 1.19.2

### ISSUE THREAD

**Issue by Davokushi** [finallion/VillagersPlus_-FORGE-#1]
Crash on the SERVER and CLIENT do not start, this is the LOG:

[[24ene.2023 10:27:31.317] [main/INFO] [cpw.mods.modlauncher.Launcher/MODLAUNCHER]: ModLauncher running: args [--launchTarget, forgeserver, --fml.forgeVersion, 43.2.3, --fml.mcVersion, 1.19.2, --fml.forgeGroup, net.minecraftforge, --fml.mcpVersion, 20220805.130853]
[24ene.2023 10:27:31.322] [main/INFO] [cpw.mods.modlauncher.Launcher/MODLAUNCHER]: ModLauncher 10.0.8+10.0.8+main.0ef7e830 starting: java version 17.0.5 by Oracle Corporation; OS Windows 10 arch amd64 version 10.0
[24ene.2023 10:27:33.154] [main/INFO] [mixin/]: SpongePowered MIXIN Subsystem Version=0.8.5 Source=union:/C:/Users/Erik/Desktop/SERVIDOR%201.19.2/libraries/org/spongepowered/mixin/0.8.5/mixin-0.8.5.jar%2363!/ Service=ModLauncher Env=SERVER
[24ene.2023 10:27:34.380] [main/WARN] [net.minecraftforge.fml.loading.moddiscovery.ModFileParser/LOADING]: Mod file C:\Users\Erik\Desktop\SERVIDOR 1.19.2\libraries\net\minecraftforge\fmlcore\1.19.2-43.2.3\fmlcore-1.19.2-43.2.3.jar is missing mods.toml file
[24ene.2023 10:27:34.386] [main/WARN] [net.minecraftforge.fml.loading.moddiscovery.ModFileParser/LOADING]: Mod file C:\Users\Erik\Desktop\SERVIDOR 1.19.2\libraries\net\minecraftforge\javafmllanguage\1.19.2-43.2.3\javafmllanguage-1.19.2-43.2.3.jar is missing mods.toml file
[24ene.2023 10:27:34.391] [main/WARN] [net.minecraftforge.fml.loading.moddiscovery.ModFileParser/LOADING]: Mod file C:\Users\Erik\Desktop\SERVIDOR 1.19.2\libraries\net\minecraftforge\lowcodelanguage\1.19.2-43.2.3\lowcodelanguage-1.19.2-43.2.3.jar is missing mods.toml file
[24ene.2023 10:27:34.396] [main/WARN] [net.minecraftforge.fml.loading.moddiscovery.ModFileParser/LOADING]: Mod file C:\Users\Erik\Desktop\SERVIDOR 1.19.2\libraries\net\minecraftforge\mclanguage\1.19.2-43.2.3\mclanguage-1.19.2-43.2.3.jar is missing mods.toml file
[24ene.2023 10:27:34.608] [main/INFO] [net.minecraftforge.fml.loading.moddiscovery.JarInJarDependencyLocator/]: Found 10 dependencies adding them to mods collection
[24ene.2023 10:27:38.363] [main/INFO] [mixin/]: Compatibility level set to JAVA_17
[24ene.2023 10:27:38.474] [main/ERROR] [mixin/]: Mixin config forge-mavapi.mixins.json does not specify "minVersion" property
[24ene.2023 10:27:38.526] [main/ERROR] [mixin/]: Mixin config forge-mavm.mixins.json does not specify "minVersion" property
[24ene.2023 10:27:38.582] [main/ERROR] [mixin/]: Mixin config rottencreatures-common.mixins.json does not specify "minVersion" property
[24ene.2023 10:27:38.584] [main/ERROR] [mixin/]: Mixin config rottencreatures.mixins.json does not specify "minVersion" property
[24ene.2023 10:27:38.700] [main/INFO] [mixin/]: Successfully loaded Mixin Connector [ca.spottedleaf.starlight.mixin.MixinConnector]
[24ene.2023 10:27:38.701] [main/INFO] [cpw.mods.modlauncher.LaunchServiceHandler/MODLAUNCHER]: Launching target 'forgeserver' with arguments []
[24ene.2023 10:27:38.726] [main/WARN] [mixin/]: Reference map 'spelunkery-forge-refmap.json' for spelunkery.mixins.json could not be read. If this is a development environment you can ignore this message
[24ene.2023 10:27:38.731] [main/WARN] [mixin/]: Reference map 'morevillagers-forge-forge-refmap.json' for morevillagers.mixins.json could not be read. If this is a development environment you can ignore this message
[24ene.2023 10:27:38.737] [main/WARN] [mixin/]: Reference map 'yungsextras.refmap.json' for yungsextras.mixins.json could not be read. If this is a development environment you can ignore this message
[24ene.2023 10:27:38.738] [main/WARN] [mixin/]: Reference map 'yungsextras.refmap.json' for yungsextras_forge.mixins.json could not be read. If this is a development environment you can ignore this message
[24ene.2023 10:27:38.740] [main/WARN] [mixin/]: Reference map 'abundant_atmosphere.refmap.json' for abundant_atmosphere.mixins.json could not be read. If this is a development environment you can ignore this message
[24ene.2023 10:27:38.746] [main/WARN] [mixin/]: Reference map 'carpeted-common-refmap.json' for carpeted-common.mixins.json could not be read. If this is a development environment you can ignore this message
[24ene.2023 10:27:38.747] [main/WARN] [mixin/]: Reference map 'carpeted-forge-refmap.json' for carpeted.mixins.json could not be read. If this is a development environment you can ignore this message
[24ene.2023 10:27:38.756] [main/WARN] [mixin/]: Reference map '${refmap_target}refmap.json' for corgilib.forge.mixins.json could not be read. If this is a development environment you can ignore this message
[24ene.2023 10:27:38.806] [main/WARN] [CanaryConfig/]: Option 'mixin.world.block_entity_ticking.world_border' requires 'mixin.util.world_border_listener=true' but found 'false'. Setting 'mixin.world.block_entity_ticking.world_border=false'.
[24ene.2023 10:27:38.807] [main/INFO] [Canary/]: Loaded configuration file for Canary: 106 options available, 0 override(s) found
[24ene.2023 10:27:38.814] [main/WARN] [mixin/]: Reference map 'v_slab_compat-common-refmap.json' for v_slab_compat-common.mixins.json could not be read. If this is a development environment you can ignore this message
[24ene.2023 10:27:38.851] [main/WARN] [mixin/]: Reference map 'everycomp-common-refmap.json' for everycomp-common.mixins.json could not be read. If this is a development environment you can ignore this message
[24ene.2023 10:27:38.852] [main/WARN] [mixin/]: Reference map 'everycomp.refmap.json' for everycomp.mixins.json could not be read. If this is a development environment you can ignore this message
[24ene.2023 10:27:38.896] [main/WARN] [mixin/]: Reference map 'mixins.fishofthieves_forge.refmap.json' for mixins.fishofthieves_forge.json could not be read. If this is a development environment you can ignore this message
[24ene.2023 10:27:38.900] [main/WARN] [mixin/]: Reference map 'rottencreatures-forge-refmap.json' for rottencreatures.mixins.json could not be read. If this is a development environment you can ignore this message
[24ene.2023 10:27:38.902] [main/WARN] [mixin/]: Reference map 'notimeoutnomore.refmap.json' for notimeoutnomore.mixins.json could not be read. If this is a development environment you can ignore this message
[24ene.2023 10:27:39.159] [main/WARN] [mixin/]: Error loading class: net/minecraft/client/model/IronGolemModel (java.lang.ClassNotFoundException: net.minecraft.client.model.IronGolemModel)
[24ene.2023 10:27:39.159] [main/WARN] [mixin/]: @Mixin target net.minecraft.client.model.IronGolemModel was not found strawgolem.mixins.json:IronGolemModelMixin
[24ene.2023 10:27:45.495] [main/INFO] [net.minecraft.util.datafix.DataFixers/]: Building unoptimized datafixer
[24ene.2023 10:27:46.873] [main/INFO] [mixin/]: Instancing error handler class com.illusivesoulworks.polymorph.mixin.IntegratedMixinPlugin
[24ene.2023 10:27:46.874] [main/FATAL] [mixin/]: Mixin apply failed villagersplus.mixins.json:StructurePoolAccessor -> net.minecraft.world.level.levelgen.structure.pools.StructureTemplatePool: org.spongepowered.asm.mixin.gen.throwables.InvalidAccessorException No candidates were found matching rawTemplates:Ljava/util/List; in net/minecraft/world/level/levelgen/structure/pools/StructureTemplatePool for villagersplus.mixins.json:StructurePoolAccessor->@Accessor[FIELD_GETTER]::getRawTemplates()Ljava/util/List; [INJECT Applicator Phase -> villagersplus.mixins.json:StructurePoolAccessor -> Apply Accessors ->  -> Locate -> villagersplus.mixins.json:StructurePoolAccessor->@Accessor[FIELD_GETTER]::getRawTemplates()Ljava/util/List;]
org.spongepowered.asm.mixin.gen.throwables.InvalidAccessorException: No candidates were found matching rawTemplates:Ljava/util/List; in net/minecraft/world/level/levelgen/structure/pools/StructureTemplatePool for villagersplus.mixins.json:StructurePoolAccessor->@Accessor[FIELD_GETTER]::getRawTemplates()Ljava/util/List; [INJECT Applicator Phase -> villagersplus.mixins.json:StructurePoolAccessor -> Apply Accessors ->  -> Locate -> villagersplus.mixins.json:StructurePoolAccessor->@Accessor[FIELD_GETTER]::getRawTemplates()Ljava/util/List;]
	at org.spongepowered.asm.mixin.gen.AccessorInfo.findTarget(AccessorInfo.java:518) ~[mixin-0.8.5.jar%2363!/:0.8.5+Jenkins-b310.git-155314e6e91465dad727e621a569906a410cd6f4]
	at org.spongepowered.asm.mixin.gen.AccessorInfo.findTargetField(AccessorInfo.java:501) ~[mixin-0.8.5.jar%2363!/:0.8.5+Jenkins-b310.git-155314e6e91465dad727e621a569906a410cd6f4]
	at org.spongepowered.asm.mixin.gen.AccessorInfo.locate(AccessorInfo.java:475) ~[mixin-0.8.5.jar%2363!/:0.8.5+Jenkins-b310.git-155314e6e91465dad727e621a569906a410cd6f4]
	at org.spongepowered.asm.mixin.transformer.MixinTargetContext.generateAccessors(MixinTargetContext.java:1389) ~[mixin-0.8.5.jar%2363!/:0.8.5+Jenkins-b310.git-155314e6e91465dad727e621a569906a410cd6f4]
	at org.spongepowered.asm.mixin.transformer.MixinApplicatorStandard.applyAccessors(MixinApplicatorStandard.java:1060) ~[mixin-0.8.5.jar%2363!/:0.8.5+Jenkins-b310.git-155314e6e91465dad727e621a569906a410cd6f4]
	at org.spongepowered.asm.mixin.transformer.MixinApplicatorStandard.applyMixin(MixinApplicatorStandard.java:398) ~[mixin-0.8.5.jar%2363!/:0.8.5+Jenkins-b310.git-155314e6e91465dad727e621a569906a410cd6f4]
	at org.spongepowered.asm.mixin.transformer.MixinApplicatorStandard.apply(MixinApplicatorStandard.java:325) ~[mixin-0.8.5.jar%2363!/:0.8.5+Jenkins-b310.git-155314e6e91465dad727e621a569906a410cd6f4]
	at org.spongepowered.asm.mixin.transformer.TargetClassContext.apply(TargetClassContext.java:383) ~[mixin-0.8.5.jar%2363!/:0.8.5+Jenkins-b310.git-155314e6e91465dad727e621a569906a410cd6f4]
	at org.spongepowered.asm.mixin.transformer.TargetClassContext.applyMixins(TargetClassContext.java:365) ~[mixin-0.8.5.jar%2363!/:0.8.5+Jenkins-b310.git-155314e6e91465dad727e621a569906a410cd6f4]
	at org.spongepowered.asm.mixin.transformer.MixinProcessor.applyMixins(MixinProcessor.java:363) ~[mixin-0.8.5.jar%2363!/:0.8.5+Jenkins-b310.git-155314e6e91465dad727e621a569906a410cd6f4]
	at org.spongepowered.asm.mixin.transformer.MixinTransformer.transformClass(MixinTransformer.java:250) ~[mixin-0.8.5.jar%2363!/:0.8.5+Jenkins-b310.git-155314e6e91465dad727e621a569906a410cd6f4]
	at org.spongepowered.asm.service.modlauncher.MixinTransformationHandler.processClass(MixinTransformationHandler.java:131) ~[mixin-0.8.5.jar%2363!/:0.8.5+Jenkins-b310.git-155314e6e91465dad727e621a569906a410cd6f4]
	at org.spongepowered.asm.launch.MixinLaunchPluginLegacy.processClass(MixinLaunchPluginLegacy.java:131) ~[mixin-0.8.5.jar%2363!/:0.8.5+Jenkins-b310.git-155314e6e91465dad727e621a569906a410cd6f4]
	at cpw.mods.modlauncher.serviceapi.ILaunchPluginService.processClassWithFlags(ILaunchPluginService.java:156) ~[modlauncher-10.0.8.jar%2354!/:10.0.8+10.0.8+main.0ef7e830]
	at cpw.mods.modlauncher.LaunchPluginHandler.offerClassNodeToPlugins(LaunchPluginHandler.java:88) ~[modlauncher-10.0.8.jar%2354!/:?]
	at cpw.mods.modlauncher.ClassTransformer.transform(ClassTransformer.java:120) ~[modlauncher-10.0.8.jar%2354!/:?]
	at cpw.mods.modlauncher.TransformingClassLoader.maybeTransformClassBytes(TransformingClassLoader.java:50) ~[modlauncher-10.0.8.jar%2354!/:?]
	at cpw.mods.cl.ModuleClassLoader.readerToClass(ModuleClassLoader.java:113) ~[securejarhandler-2.1.4.jar:?]
	at cpw.mods.cl.ModuleClassLoader.lambda$findClass$15(ModuleClassLoader.java:219) ~[securejarhandler-2.1.4.jar:?]
	at cpw.mods.cl.ModuleClassLoader.loadFromModule(ModuleClassLoader.java:229) ~[securejarhandler-2.1.4.jar:?]
	at cpw.mods.cl.ModuleClassLoader.findClass(ModuleClassLoader.java:219) ~[securejarhandler-2.1.4.jar:?]
	at cpw.mods.cl.ModuleClassLoader.loadClass(ModuleClassLoader.java:135) ~[securejarhandler-2.1.4.jar:?]
	at java.lang.ClassLoader.loadClass(ClassLoader.java:520) ~[?:?]
	at net.minecraft.world.level.levelgen.structure.structures.JigsawStructure.m_227639_(JigsawStructure.java:28) ~[server-1.19.2-20220805.130853-srg.jar%23505!/:?]
	at com.mojang.serialization.codecs.RecordCodecBuilder.mapCodec(RecordCodecBuilder.java:76) ~[datafixerupper-5.0.28.jar%2375!/:?]
	at net.minecraft.world.level.levelgen.structure.structures.JigsawStructure.<clinit>(JigsawStructure.java:27) ~[server-1.19.2-20220805.130853-srg.jar%23505!/:?]
	at net.minecraft.data.worldgen.Structures.<clinit>(Structures.java:71) ~[server-1.19.2-20220805.130853-srg.jar%23505!/:?]
	at net.minecraft.data.BuiltinRegistries.m_236009_(BuiltinRegistries.java:87) ~[server-1.19.2-20220805.130853-srg.jar%23505!/:?]
	at net.minecraft.data.BuiltinRegistries.m_236004_(BuiltinRegistries.java:114) ~[server-1.19.2-20220805.130853-srg.jar%23505!/:?]
	at java.util.LinkedHashMap.forEach(LinkedHashMap.java:721) ~[?:?]
	at net.minecraft.data.BuiltinRegistries.<clinit>(BuiltinRegistries.java:113) ~[server-1.19.2-20220805.130853-srg.jar%23505!/:?]
	at net.minecraft.core.Registry.<clinit>(Registry.java:665) ~[server-1.19.2-20220805.130853-srg.jar%23505!/:?]
	at net.minecraft.server.Bootstrap.m_135870_(Bootstrap.java:43) ~[server-1.19.2-20220805.130853-srg.jar%23505!/:?]
	at net.minecraft.server.Main.main(Main.java:110) ~[server-1.19.2-20220805.130853-srg.jar%23505!/:?]
	at jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:?]
	at jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:77) ~[?:?]
	at jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[?:?]
	at java.lang.reflect.Method.invoke(Method.java:568) ~[?:?]
	at net.minecraftforge.fml.loading.targets.CommonServerLaunchHandler.lambda$launchService$0(CommonServerLaunchHandler.java:29) ~[fmlloader-1.19.2-43.2.3.jar%2367!/:?]
	at cpw.mods.modlauncher.LaunchServiceHandlerDecorator.launch(LaunchServiceHandlerDecorator.java:30) [modlauncher-10.0.8.jar%2354!/:?]
	at cpw.mods.modlauncher.LaunchServiceHandler.launch(LaunchServiceHandler.java:53) [modlauncher-10.0.8.jar%2354!/:?]
	at cpw.mods.modlauncher.LaunchServiceHandler.launch(LaunchServiceHandler.java:71) [modlauncher-10.0.8.jar%2354!/:?]
	at cpw.mods.modlauncher.Launcher.run(Launcher.java:106) [modlauncher-10.0.8.jar%2354!/:?]
	at cpw.mods.modlauncher.Launcher.main(Launcher.java:77) [modlauncher-10.0.8.jar%2354!/:?]
	at cpw.mods.modlauncher.BootstrapLaunchConsumer.accept(BootstrapLaunchConsumer.java:26) [modlauncher-10.0.8.jar%2354!/:?]
	at cpw.mods.modlauncher.BootstrapLaunchConsumer.accept(BootstrapLaunchConsumer.java:23) [modlauncher-10.0.8.jar%2354!/:?]
	at cpw.mods.bootstraplauncher.BootstrapLauncher.main(BootstrapLauncher.java:141) [bootstraplauncher-1.1.2.jar:?]

**Comment by finallion** [comment]
Can you post the full log please?
The mixin that crashes is a standard, used in other mods as well, and I can't reproduce the error. So I'm assuming there is a incompat with some other mod. Does the mod crash for you by itself?

**Comment by finallion** [comment]
And just to make sure, does it also crash on Forge 43.2.0?

**Comment by finallion** [comment]
@xenornithos could you please post your logs, too?

**Comment by Reshirou** [comment]
I also crash on launch, and without optifine.

**Comment by finallion** [comment]
I uploaded a new jar file (replaced the old one). Let me know if this fixes the crash. Its hard for me to tell, as I'm still unable to reproduce the error myseld.
